162 GitHub actions
NilFoundation/crypto3-zk pull request #163
Opened 2023-08-09 11:27 UTC by ETatuzova

2023-08-09 11:51 UTC, martun requested changes

2023-08-09 11:51 UTC, martun commented on .github/workflows/run_tests.yml
> +        run: |
We don't need these changes, all we needed was adding blueprint, which we better try to remove as well, by removing dependency on it.

2023-08-10 06:40 UTC, ETatuzova commented
Checks are not successfull because we need NilFoundation/crypto3#61 be merged to master before

2023-08-10 09:32 UTC, martun approved these changes

2023-08-10 09:53 UTC, merged